//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEvo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public Asiento()
        {
            this.Entrada = new HashSet<Entrada>();
        }
    
        public int idAsiento { get; set; }
        public string codigo { get; set; }
        public int idSala { get; set; }
        public string estado { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual ICollection<Entrada> Entrada { get; set; }
    }
}
