//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEvo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Pelicula = new HashSet<Pelicula>();
        }
    
        public int idCategoria { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Pelicula> Pelicula { get; set; }
    }
}
