//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEvo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        public int idEntrada { get; set; }
        public int idAsiento { get; set; }
        public int idFuncion { get; set; }
        public int idTipoEntrada { get; set; }
        public string estado { get; set; }
        public int idVenta { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual TipoEntrada TipoEntrada { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
