//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEvo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.Entrada = new HashSet<Entrada>();
        }
    
        public int idFuncion { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaFuncion { get; set; }
        public string hora { get; set; }
        public int idTipoFuncion { get; set; }
        public int idPelicula { get; set; }
        public int idSala { get; set; }
    
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual TipoFuncion TipoFuncion { get; set; }
    }
}
