//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEvo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Asiento = new HashSet<Asiento>();
            this.Funcion = new HashSet<Funcion>();
        }
    
        public int idSala { get; set; }
        public int capacidad { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public int asientosLibres { get; set; }
        public int idCine { get; set; }
    
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Cine Cine { get; set; }
        public virtual ICollection<Funcion> Funcion { get; set; }
    }
}
